/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package whatodo.ui;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import whatodo.logic.Task;

/**
 *
 * @author esva
 */
public class AddTask extends javax.swing.JFrame {

    private String newHeading;
    private Date expiration;
    private Task task;

    public AddTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JTextField();
        info = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        prio = new javax.swing.JComboBox<>();

        heading.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        heading.setText("Otsikko");

        info.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        info.setText("Tarkennus");
        info.setToolTipText("");

        create.setText("Valmis");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        prio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prio 1", "Prio 2", "Prio 3" }));
        prio.setSelectedIndex(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(prio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(create)
                        .addGap(32, 32, 32))
                    .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addComponent(heading))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(prio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        if (!correctHeading(heading.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Otsikko ei saa olla tyhjä tai yli 20 merkkiä pitkä!");
        } else if (!correctDesc(info.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Tarkennus ei saa olla tyhjä tai yli 100 merkkiä pitkä!");
        } else {
            String prior = (String) prio.getSelectedItem();
            int priority;
            if (prior.contains("1")) {
                priority = 1;
            } else if (prior.contains("2")) {
                priority = 2;
            } else {
                priority = 3;
            }
            this.task = new Task(heading.getText(), new Date(), priority, info.getText());
        }
        setVisible(false);
    }//GEN-LAST:event_createActionPerformed

    private boolean correctHeading(String heading) {
        if (heading.isEmpty() || heading.length() > 20) {
            return false;
        } else {
            return true;
        }
    }

    private boolean correctDesc(String desc) {
        if (desc.length() > 100 || desc.isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    public Task getTask() {
        return this.task;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTask().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JTextField heading;
    private javax.swing.JTextField info;
    private javax.swing.JComboBox<String> prio;
    // End of variables declaration//GEN-END:variables
}
